---

name: pygmy
on:
  push:
  pull_request:
    schedule:
    - cron: '0 0 * * *'
jobs:
  pygmyBuild:
    name: Build Pipeline
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Test build processes.
        run: docker build -t archtest .

  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_USERNAME: pygmy-bot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}